# Generated by Django 5.2.7 on 2025-11-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_address', models.TextField()),
                ('school_phone', models.CharField(max_length=20)),
                ('school_email', models.EmailField(max_length=254)),
                ('class_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('both', 'Both')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
