# Generated by Django 5.2.7 on 2025-11-14 16:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_careerapplication_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='application_letter',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
